### ISSUE TITLE
Tem como adicionar função de dar ban! 

### ISSUE THREAD

**Issue by DerexScript** [billbarsch/myzap#1]
Gostaria de deixar um bot administrando um grupo meu! 
E gostaria que ele desse ban para quem falar certas palavras...

**Comment by billbarsch** [comment]
tem como sim
na documentação do venom que é usado nesse projeto ele tem essa função aqui de remover usuarios de grupos:

await client.removeParticipant(groupId, '123123@c.us');

se vc usar isso junto com a função de ler mensagens de grupos vc consegue fazer o que vc quer.
nossa api ainda está bem no início, basicamente so tem a primeira função que é de enviar mensagem, hoje ja vou colocar mais algumas que vou utilizar mais
