### ISSUE TITLE
After QR scan status has not change

### ISSUE THREAD

**Issue by jayanisanjay** [billbarsch/myzap#10]
After QR scan status has not change
So Sentmessage and sendfile is not working

**Comment by AlanMartines** [comment]
Meu fork do myzap que estou montando o bot do whats, caso queiram dar uma olhada segue o link do projeto [mywhats](https://github.com/AlanMartines/mywhats)

My myzap fork I'm setting up the whats bot for, if you want to take a look follow project link [mywhats](https://github.com/AlanMartines/mywhats)
