### ISSUE TITLE
Não gera o qrcode

### ISSUE THREAD

**Issue by luangouveas** [billbarsch/myzap#123]
Quando faço a requisição ao método start ele não gera o qrcode e fica em um loop infinito

![image](https://user-images.githubusercontent.com/20728305/141334158-cf5e81e4-c9c6-4b5b-8016-9959c81d996c.png)

**Comment by augustofcs** [comment]
Estou com o mesmo problema, testei usar o venom pra ver se resolvia, ao tentar usar o venom, o qrcode é gerado, mas não envia webhook de conectado

**Comment by lunosat** [comment]
Atualize as dependências.

`npm update`

**Comment by Monteiroemelo** [comment]
@luangouveas Você conseguiu resolver?

**Comment by fumagally** [comment]
Também estou com o mesmo problema só fica nesta tela abaixo... já fiz o apt upgrade conforme o @AkirahX citou mas continua o problema...

![image](https://user-images.githubusercontent.com/3512770/142220082-bcd378e1-73ed-405d-8821-d5b60e4c6c9a.png)

**Comment by jhowbhz** [comment]
Amigo, @fumagally faz o seguinte.


```rm -R node_modules```

```npm install --unsafe-perm=true --allow-root```

E posta pra gente o resultado;

**Comment by fumagally** [comment]
> Amigo, @fumagally faz o seguinte.
> 
> `rm -R node_modules`
> 
> `npm install --unsafe-perm=true --allow-root`
> 
> E posta pra gente o resultado;

Executei aqui brother.. ainda continua.. como abaixo:

![image](https://user-images.githubusercontent.com/3512770/142221862-220f65dd-d9c7-4a7c-9f07-b177bd87d145.png)

**Comment by jhowbhz** [comment]
Eu hein, força o update então... rsrs


```npm update @wppconnect-team/wppconnect --force ```

**Comment by fumagally** [comment]
> Eu hein, força o update então... rsrs
> 
> `npm update @wppconnect-team/wppconnect --force `

Agora sim brother.. deu certo.. porém ao ler o QRCODE me retorna o erro abaixo, sabe me dizer o que seria?

![image](https://user-images.githubusercontent.com/3512770/142223309-4e3bd9f4-96fe-4761-bbc2-94c08b8a254f.png)

**Comment by jhowbhz** [comment]
Você está fazendo a request errada amigo! 

```Verifique o header```

![image](https://user-images.githubusercontent.com/31408451/142223940-3db44f62-03f8-4a10-8943-d4dd5ef2154a.png)

```Verifique o body```

![image](https://user-images.githubusercontent.com/31408451/142224047-7b1e7a64-2bb3-4b02-9c9d-d6a717d12fbf.png)

**Comment by lunosat** [comment]
> Também estou com o mesmo problema só fica nesta tela abaixo... já fiz o apt upgrade conforme o @AkirahX citou mas continua o problema...
> 
> ![image](https://user-images.githubusercontent.com/3512770/142220082-bcd378e1-73ed-405d-8821-d5b60e4c6c9a.png)
> 

Era `npm update` .-.

**Comment by fumagally** [comment]
> > Também estou com o mesmo problema só fica nesta tela abaixo... já fiz o apt upgrade conforme o @AkirahX citou mas continua o problema...
> > ![image](https://user-images.githubusercontent.com/3512770/142220082-bcd378e1-73ed-405d-8821-d5b60e4c6c9a.png)
> 
> Era `npm update` .-.

Depois que executei nesta sequencia aqui funcionou a exibição do QRCODE @AkirahX 
`rm -R node_modules`
`npm install --unsafe-perm=true --allow-root`
 `npm update @wppconnect-team/wppconnect --force`

**Comment by fumagally** [comment]
Minhas configurações parecem estar tudo ok @jhowbhz .. mas o erro continua.. estou usando a ultima versão que usa as variables:

![image](https://user-images.githubusercontent.com/3512770/142228655-a93129a5-1f07-486b-bf72-20dc5dc91f46.png)

![image](https://user-images.githubusercontent.com/3512770/142228424-de097ae3-b29b-4ef2-9b51-e1881b3ce4f8.png)

![image](https://user-images.githubusercontent.com/3512770/142228818-8b21f4b8-e938-4b3e-b595-a63d225ab3e8.png)

**Comment by luangouveas** [comment]
Também consegui realizando esses passos, porém apenas o sendText não funciona
Exemplo:

Retorno com erro 500
![image](https://user-images.githubusercontent.com/20728305/142229734-8010f654-b390-4a1a-acb4-8b84d8dcfbdf.png)

Retorno com erro 500 porém envia
![image](https://user-images.githubusercontent.com/20728305/142230100-030b44e5-33d6-4458-8431-9394106c2fdf.png)

Retorno com sucesso
![image](https://user-images.githubusercontent.com/20728305/142230161-d0debd6e-6ca3-4dad-b59b-e11314c629e6.png)

**Comment by fumagally** [comment]
> Também consegui realizando esses passos, porém apenas o sendText não funciona Exemplo:
> 
> Retorno com erro 500 ![image](https://user-images.githubusercontent.com/20728305/142229734-8010f654-b390-4a1a-acb4-8b84d8dcfbdf.png)
> 
> Retorno com erro 500 porém envia ![image](https://user-images.githubusercontent.com/20728305/142230100-030b44e5-33d6-4458-8431-9394106c2fdf.png)
> 
> Retorno com sucesso ![image](https://user-images.githubusercontent.com/20728305/142230161-d0debd6e-6ca3-4dad-b59b-e11314c629e6.png)

Também estou com o mesmo problema do Erro 500 agora amigo... conseguiu resolver no seu?

**Comment by jhowbhz** [comment]
Resolveu o problema?

**Comment by andersoncosta** [comment]
Estava com o mesmo problema no Ubuntu 18, atualizei para o Ubuntu 20.04 e com as recomendações abaixo 
rm -R node_modules
npm install --unsafe-perm=true --allow-root
npm update @wppconnect-team/wppconnect --force

funcionou muito bem o QR Code e conseguir enviar as mensagens também.

**Comment by AlbertEinsteinGlitchPoint** [comment]
Boa noite

estou testando o sistema em um servidor ubuntu 20.04 dentro da minha rede interna.. com IP iterno 192.168.xx.xxx   não consigo gerar o qr.code só fica em 


info:     [session1:browser] Initializing browser...
0|index  | info:     [session1:client] Initializing...


e na página web do myzap 2.0 só fica girando... teve uma vez que apareceu whatsapp web 2.1.xxx mas não passou disso..

tem que ter IP publico na máquina? portas liberadas?

**Comment by renenucci** [comment]
> Boa noite
> 
> estou testando o sistema em um servidor ubuntu 20.04 dentro da minha rede interna.. com IP iterno 192.168.xx.xxx não consigo gerar o qr.code só fica em
> 
> info: [session1:browser] Initializing browser... 0|index | info: [session1:client] Initializing...
> 
> e na página web do myzap 2.0 só fica girando... teve uma vez que apareceu whatsapp web 2.1.xxx mas não passou disso..
> 
> tem que ter IP publico na máquina? portas liberadas?

Conseguiu resolver? o meu ficou no mesmo ponto, depois de forçar o update no npm até passou mas não gera o QR.

Fica:
...
info:     [NomeSessao1:client] WhatsApp WEB version: 2.2216.8
info:     [NomeSessao1:client] WA-JS version: 2.2.2

**Comment by renenucci** [comment]
![image](https://user-images.githubusercontent.com/18505538/168618821-3f6d4f20-cb7d-45f1-9b52-61589711dadc.png)

**Comment by BrunoSRibeiro** [comment]
Boa tarde!

Executei a instalação do myzap, mas na página para criar o QRCODE recebo o erro 404.
Depurando a página percebi que está chamando duas vezes o endereço da URL.
O QRCODE é gerado normalmente por curl.

![image](https://user-images.githubusercontent.com/21297879/187511466-7ca6e962-fd74-4342-adb6-be16a3172170.png)

**Comment by jhowbhz** [comment]
Seu arquivo .env está configurado errado.

**Comment by BrunoSRibeiro** [comment]
@jhowbhz 

Bingo.
Eu fiz a instalação utilizando o script de instalação automatizada e o mesmo não adicionou o http://.

Obrigado pela atenção.
