### ISSUE TITLE
Não conecta para gerar o QRCode

### ISSUE THREAD

**Issue by Monteiroemelo** [billbarsch/myzap#135]
Aparentemente tudo ok, nada e erros na instalação e configuração ( .env incluindo o banco de dados ) porém ao tentar conectar com http://ip-do-servidor:3333/start nem erro de token aparece, ou seja não conecta para gerar o QRCode.

Ubuntu 20.4

[img ](https://monteiroemelo.com.br/myzap.png)

**Comment by jhowbhz** [comment]
Bom dia amigo, qual token vc configurou na API?

**Comment by Monteiroemelo** [comment]
TOKENMYZAP o mesmo colocado no .env.

**Comment by jhowbhz** [comment]
Mas na requisição você usou outro token `d`

**Comment by Monteiroemelo** [comment]
Coloquei daquela forma na imagem, para demonstrar justamente que não aparece nem o erro do token, quando coloca errado o sistema avisa, nem isso acontece é como se não tivesse conecta ao servidor, porém temos o id da sessão. Isso q não sei mais verificar.

**Comment by Monteiroemelo** [comment]
Já reinstalei os navegadores  WPPCONNECT e Venom, fazendo as devidas alterações no .env e nada de iniciar o navegardor para gerar o qrcode.

**Comment by jhowbhz** [comment]
Você consegue me mostrar o console do navegador?

**Comment by Monteiroemelo** [comment]
https://monteiroemelo.com.br/myzap.png

**Comment by jhowbhz** [comment]
Preciso ver o console do seu navegador.

**Comment by Monteiroemelo** [comment]
ok. Meu ambiente era um VMWare dentro do windows2016, agora estou formatando para windows10. Assim que terminar compartilho com vc. Obrigado por enquanto.!

**Comment by jhowbhz** [comment]
Nada. Qualquer coisa chama no wpp.
https://wa.me/5531995360492

se quiser consumir o serviço sem instalar, basta usar o https://apigratis.com.br

**Comment by Monteiroemelo** [comment]
Então, não consegui usar o apigratis, se tiver um tutorial agradeço.

**Comment by jhowbhz** [comment]
Me chama no whats, que eu te dou um help.... qual problema lá?

**Comment by Monteiroemelo** [comment]
Mesmo depois de formatado e feito varias instalações limpa, nada.

https://github.com/billbarsch/myzap/issues/64#issue-870491566

**Comment by jhowbhz** [comment]
Resolvido na issue #136
