### ISSUE TITLE
Navegador não inicia.

### ISSUE THREAD

**Issue by Monteiroemelo** [billbarsch/myzap#136]
Navegador não inicia.

Erro e teste => http://monteiroemelo.com.br/navegador.png

**Comment by jhowbhz** [comment]
Desligue o firewall do Windows

**Comment by Monteiroemelo** [comment]
Desativei das redes Públicas e Privadas, ainda continua o problema.

**Comment by jhowbhz** [comment]
Preciso ver o seu ambiente pra entender a comunicação entre os devices. Assim sem logs, prints, etc... Fica super complicado

**Comment by jhowbhz** [comment]
Basta inserir o `http ou https` na variável `host` no seu arquivo `.env`
