### ISSUE TITLE
O emparelhamento não funciona

### ISSUE THREAD

**Issue by david756** [billbarsch/myzap#140]
Olá, estava funcionando bem, mas agora tento conectar e fica em uma mensagem que diz

✓ [instance: session1]: Connected

mas não mostra o token e não o cria na pasta de tokens, não continua o processo e, portanto, a conexão não funciona. sua ajuda por favor

![image](https://user-images.githubusercontent.com/19328634/144940056-d05b0720-496d-4bcd-b37a-02cc3540e929.png)

**Comment by Demarky** [comment]
Estou com o mesmo problema, conseguiu resolver?
