### ISSUE TITLE
Recebo um erro ao tentar usar com certificado SSL

### ISSUE THREAD

**Issue by Sulivan1999** [billbarsch/myzap#141]
Olá, eu recebo um erro ao ativar a cerificação SSL. As credencias "cert.pem" e "privkey.pem" estão corretas, pois uso na versão anterior da API sem nenhum problema.

O erro que recebo:
![erro myzap](https://user-images.githubusercontent.com/58372000/145054006-18d14efd-f841-4d94-b935-0d0d2bda3d85.png)

**Comment by flaberson** [comment]
Tenta adicionar isso amigo: 
const https = require(`https`);
const fs = require(`fs`);

**Comment by brunobgr** [comment]
Olá, aqui acontece o mesmo erro, não estou usando proxy, ativei o certificado não funciona quando muda o arquivo .env
da este erro 


> Olá, eu recebo um erro ao ativar a cerificação SSL. As credencias "cert.pem" e "privkey.pem" estão corretas, pois uso na versão anterior da API sem nenhum problema.
> 
> O erro que recebo: ![erro myzap](https://user-images.githubusercontent.com/58372000/145054006-18d14efd-f841-4d94-b935-0d0d2bda3d85.png)

Aqui está ocorrendo o mesmo erro na minha VPS, alguém pra nos ajudar? Obrigado

**Comment by w3llfernandes** [comment]
Fiz como mencionou mas retorna o erro:
ERR_INVALID_ARG_TYPE

**Comment by SheikSystem** [comment]
Alguem conseguiu resolver?

**Comment by jhowbhz** [comment]
Você deve setar essa informação no seu arquivo ```.env```
