### ISSUE TITLE
Auto Reconnect com MD

### ISSUE THREAD

**Issue by iamedusm** [billbarsch/myzap#145]
Olá o sistema não consegue iniciar a seção automaticamente se estiver conectado com MD ele gera novo QR Code pra fazer Login, porem já existe uma seçao aberta tanto no FireBase qunto no App do Whats, alguem já conseguiu resolver esse problema ?

**Comment by 6000850** [comment]
hello
how to solve this problem ?

**Comment by taknamecom** [comment]
I have this problem too

**Comment by taknamecom** [comment]
I solved it with add this line to engines/WppConnect.js

                puppeteerOptions: { userDataDir: './tokens/' + session, },

before createPathFileToken: false,
