### ISSUE TITLE
multi device not working

### ISSUE THREAD

**Issue by 6000850** [billbarsch/myzap#153]
Today, after it was automatically unpired, when I tried to scan qrcode again, but the connection was not established and I try to scan the code again, but it still does not work.

**Comment by taknamecom** [comment]
hello

I solved it with add this line to engines/WppConnect.js

                puppeteerOptions: { userDataDir: './tokens/' + session, },

before createPathFileToken: false,

**Comment by faelfernandes** [comment]
> hello
> 
> I solved it with add this line to engines/WppConnect.js
> 
> ```
>             puppeteerOptions: { userDataDir: './tokens/' + session, },
> ```
> 
> before createPathFileToken: false,

Muito bom, isto resolveu para mim. Obrigado!
