### ISSUE TITLE
Erro ao start WppConnect no MyZap2.0

### ISSUE THREAD

**Issue by alissoncleiton** [billbarsch/myzap#161]
ndex  | Webhook no defined
0|index  | webhooks status message....
0|index  | info:     [session1:session] Session Unpaired
0|index  | qrReadSuccess
0|index  | info:     [session1:client] Auto close configured to 90s
0|index  | inChat
0|index  | Webhook no defined
0|index  | webhooks connect status....
0|index  | TypeError: Cannot read properties of undefined (reading 'user')
0|index  |     at Function.start (/root/MyZap2.0/engines/WppConnect.js:105:64)
0|index  |     at runMicrotasks (<anonymous>)
0|index  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|index  |     at async init (/root/MyZap2.0/routers/WppConnect.js:74:36)

O por que do erro acima? Alguém consegue me ajudar.

**Comment by SheikSystem** [comment]
estou com mesmo erro voce conseguiu resolver? ou alguem que possa ajudar nos nesse erro?

**Comment by alissoncleiton** [comment]
Boa tarde, edita o arquivo engines/WppConnect.js na linha 105 e remover o 'user' da lista de parâmetros. Fiz isso e funcionou normalmente.

**Comment by alanpereiracoelho** [comment]
WhatsApp WEB version: undefined na hora do start, mais alguem?

**Comment by gabrielnm123** [comment]
Estou com o mesmo erro, e o que  @alissoncleiton  disse falou não funcionou

![image](https://user-images.githubusercontent.com/70154660/186770463-fdbd3e75-eebc-4c99-bb89-2aacdb91da11.png)

Alguem resolveu isso?

**Comment by alissoncleiton** [comment]
Oi pessoal, boa noite, desculpa a demora na resposta, é simples de resolver. 

Vamos lá.

Editem o arquivo **/root/MyZap2.0/engines/WppConnect.js**

Acha a linha **_webhooks.wh_connect(session, 'connected', info.wid.user, browser, tokens)_** e edita ela para ficar assim: **webhooks.wh_connect(session, 'connected', browser, tokens)** aí depois da alteração salva e fecha o arquivo aí só reiniciar o serviço e pronto, tá resolvido.

**Comment by gabrielnm123** [comment]
Boa noite  @alissoncleiton  agora da esse erro

`Error [FirebaseError]: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field sessionkey in document Sessions/5)`

**Comment by alissoncleiton** [comment]
> Boa noite @alissoncleiton agora da esse erro
> 
> `Error [FirebaseError]: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field sessionkey in document Sessions/5)`

Te aconselho a fazer a instalação por este repositório: https://github.com/edupoli/MyZap2.0

Só muda o seguinte passo, primeiro vc começa por este passo: "Para instalar o nodejs 16". Depois as "Dependências" o "Para instalar o ChomeDrive" 

No passo: "Clonar do GIT" você vai corrigir este comando "cp env_exemplo .env" para "cp .env_exemplo .env" observa que tem o ponto antes do env_exemplo.

Depois que vc terminar de instalar tudo, você executa os seguintes comandos:

Dentro da pasta MyZap2.0 você executa:

pm2 stop index.js

npm update @wppconnect-team/wppconnect --force

(Depois que vc executar a atualização do wppconnect edita o arquivo WppConnect.js e faz o ajuste que indiquei.)

pm2 start index.js

Assim seu MyZap2.0 vai funcionar perfeito. Já tenho 6 servidores funcionando e mais de 50 sessões.
