### ISSUE TITLE
Conectar Dominio com https

### ISSUE THREAD

**Issue by SheikSystem** [billbarsch/myzap#163]
Ola alguem poderia me dar um help, deixei tudo funcional porem quando vou solicitar o qrcode por jquery e socket a açao é bloqueada porque no site onde estou solicitando tem https e nao conecta com link sem https, e por sua vez tento fazer o api funcionar com https porem recebo erros que no servidor ao iniciar novamente.

 TypeError: https.createServer is not a function
0|index  |     at Object.<anonymous> (/root/MyZap2.0/index.js:66:11)
0|index  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
0|index  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
0|index  |     at Module.load (node:internal/modules/cjs/loader:981:32)
0|index  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
0|index  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|index  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
0|index  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
0|index  |     at Module.load (node:internal/modules/cjs/loader:981:32)
0|index  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
0|index  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
0|index  |     at node:internal/main/run_main_module:17:47
PM2      | App [index:0] exited with code [1] via signal [SIGINT]
PM2      | App [index:0] starting in -fork mode-
PM2      | App [index:0] online

Alguem pode me ajudar de como proceder?

**Comment by SheikSystem** [comment]
polling-xhr.js:157 Mixed Content: The page at 'https://www.dominio.com/whatsapp' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ipserver:3333/socket.io/?EIO=4&transport=polling&t=O25WMHF'. This request has been blocked; the content must be served over HTTPS.

Quando tento usar sem ter ssl recebo essa mensagem no console do navegador.

**Comment by JulianoBazzi** [comment]
Para configurar o HTTPS, você tem que fazer o seguinte:

Ter configurado o certificado SSL no servidor em que esta rodando a aplicação MyZap.

.env
`PORT=3333
HOST=https://seu.dominio.app.br
DOMAIN_SSL=seu.dominio.app.br
HTTPS=0`

views/index.ejs
![image](https://user-images.githubusercontent.com/16826201/166306879-613abc6d-0481-47f5-a3f6-fd3036edb08f.png)
Remover o trecho "url +"

Segue o passo do arquivo de configuração simples do link abaixo (utilizar o myzap.conf):
https://github.com/AlanMartines/myzap/tree/myzap2.0/nginx

Feito isso você vai conseguir acessar via HTTPS seu domínio

**Comment by SheikSystem** [comment]
Vou tentar fazer-lo como sitado acima e volto a responder se funcionou..

**Comment by SheikSystem** [comment]
> JulianoBazzi

Estou notando que voce mandou de uma versao diferente essa que mencionei o erro é a versao 2.0 que apresenta esse erro somente quando eu coloco:
 # Caso utilize certificado SSL defina a variavel HTTPS=1 e informe o diretorio nas variaveis 
HTTPS=1
Seto 1 nessa opçao dai descomento os locais dos certificados logo abaixo. dai ja aprensenta esse erro que mencionei acima.

**Comment by JulianoBazzi** [comment]
O HTTPS=1 do MyZap 2.0 não funciona, o comando que te passei é para fazer funcionar o HTTPS do Nginx
