### ISSUE TITLE
Muitos banimentos através da api usando WPPConnect 

### ISSUE THREAD

**Issue by Jhonata-Jackson** [billbarsch/myzap#167]
Estou utilizando para realizar alguns disparos e notei que minhas sessões estavam sendo derrubadas e quando fui ver as intâncias que eu subi estão sendo banidas, alguém pode me ajudar?

**Comment by tiagocaus** [comment]
Qual empresa está usado?

**Comment by Jhonata-Jackson** [comment]
> Qual empresa está usado?

Como assim?
Quem está usando a API ou qual empresa de números virtuais estou usando?
