### ISSUE TITLE
Wppconnect não continua ...

### ISSUE THREAD

**Issue by irineugranato** [billbarsch/myzap#168]
Estou usando um ubuntu na Lightsail amazon.. porta 3333 liberada
Página web entra normalmente pedindo nome token e key 

Após  reencher tudo e clicar em enviar para obter o qrcode, o servidor fica parado neste status

0|index  | info:     
0|index  |   _       ______  ____  ______                            __ 
0|index  |   | |     / / __ \/ __ \/ ____/___  ____  ____  ___  _____/ /_
0|index  |   | | /| / / /_/ / /_/ / /   / __ \/ __ \/ __ \/ _ \/ ___/ __/
0|index  |   | |/ |/ / ____/ ____/ /___/ /_/ / / / / / / /  __/ /__/ /_  
0|index  |   |__/|__/_/   /_/    \____/\____/_/ /_/_/ /_/\___/\___/\__/
0|index  | info:     [session1:browser] Initializing browser...
0|index  | info:     [session1:client] Initializing...
0|index  | info:     [session1:client] WhatsApp WEB version: 2.2126.14

daí não segue mais e não aparece o qrcode...

Alguém já passou por este problema ?

**Comment by jhowbhz** [comment]
Atualize a versao

```npm update @wppconnect-team/wppconnect --force```
