### ISSUE TITLE
Não inicia a sessão

### ISSUE THREAD

**Issue by juridicodiniz** [billbarsch/myzap#170]
Testando no Insomnia, quando clico em "Send" para iniciar a sessão, fica processando "a vida toda".

No servidor aparece a mensagem de erro:  connect ECONNREFUSED 127.0.0.1:56807

A porta muda toda vez que tento inicar a sessão,  já tentei na 56886, 56373, etc.

Alguém já teve esse problema?

Att, Fernando Diniz

**Comment by jhowbhz** [comment]
Já sim, atualiza ou instala o seu google chrome, lembrando que o processo pra rodar em WSL do windows é diferente.

```bash
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
```

```bash
sudo apt install ./google-chrome-stable_current_amd64.deb```
