### ISSUE TITLE
getAllGroups retorna 400

### ISSUE THREAD

**Issue by alisson-acioli** [billbarsch/myzap#171]
Estou enviando corretamente a sessão via POST JSON para o endpoint **/getAllGroups**.

O problema é que só me retorna

```
{
	"result": 400,
	"status": "FAIL",
	"error": {}
}

```
Pelo que vi fazendo uns debugs o problema é no arquivo **functions/WPPConnect/groups.js** na linha **const response = await data.client.getAllGroups();**

Tem alguém que conseguiu arrumar esse bug ?

**Comment by jhowbhz** [comment]
Algumas funções pararam de funcionar devivo a essa update do multiplos devices
