### ISSUE TITLE
Send to Whatsapp Group

### ISSUE THREAD

**Issue by andrevader78** [billbarsch/myzap#175]
Is there a possible to send a Whatsapp Group ?

**Comment by jhowbhz** [comment]
Yes, set isGroup:true, in body json

**Comment by andrevader78** [comment]
> Yes, set isGroup:true, in body json

Hi, like this?

{
    "session" : "test",
    "number" : "xxx-xxxxx",
    "text" : "Mensagem de Teste"
    "isGroup" : true
}

**Comment by Alvaro369** [comment]
Could you add an example how the definition in numeroa would be for the group? Do I have to change the group name?
