### ISSUE TITLE
QR code em loop

### ISSUE THREAD

**Issue by felipesyss** [billbarsch/myzap#176]
Apos fazer a leitura do QR, é informado um novo QR code, após a leitura do novo QR code, a seguinte mensagem é exibida: 

`error:    Unhandled Rejection: FirebaseError: Function setDoc() called with invalid data. Unsupported field value: undefined (found in field wh_status in document Sessions/TESTE)
`

Alguma sugestão?

**Comment by jhowbhz** [comment]
Poste como está fazendo sua requisição por favor.

**Comment by leicam** [comment]
Estou configurando a aplicação e recebi o mesmo erro, estou enviando os dados de sessão desta forma
![image](https://user-images.githubusercontent.com/7016313/190498927-5d505368-4684-431f-88bd-d868322399bf.png)
