### ISSUE TITLE
firebase error

### ISSUE THREAD

**Issue by guto2902** [billbarsch/myzap#178]
Unhandled Rejection: FirebaseError: Function setDoc() called with invalid data. Unsupported field value: undefined (found in field sessionkey in document Sessions/suporte5)

**Comment by leandrodesign** [comment]
MESMO PROBLEMA AQUI

**Comment by jhowbhz** [comment]
Verifique sua requisição, poste aqui como você está fazendo a request.

**Comment by pablomatias** [comment]
Mesmo erro aqui, logo após ler o QrCode no log do pm2 aparece o seguinte erro

error:    Unhandled Rejection: FirebaseError: Function setDoc() called with invalid data. Unsupported field value: undefined (found in field WABrowserId in document Sessions/pablo2)

verifiquei as credenciais do firebase estão todas ok, tambem verifiquei o projeto do firebase e não tem nada gravado lá

**Comment by leicam** [comment]
Mesmo erro, assim é como estou enviando a requisição, após a leitura do QrCode no aparelho é apresentada está mensagem
"unhandled rejection firebase error function setDoc() called with invalid data"
![image](https://user-images.githubusercontent.com/7016313/190499563-858075a7-d46e-402b-a6d9-ff7736f23a1e.png)

**Comment by leonardodevbr** [comment]
Tive o mesmo problema, mas consegui solucionar adicionando o sessionkey no header da request /start tmb.
