### ISSUE TITLE
Chat em JS ou jQuery ?

### ISSUE THREAD

**Issue by ftbarata** [billbarsch/myzap#182]
Olá pessoal, estou procurando um plugin ou alguma coisa para fazer o chat em que o backend seja o myzap, ou seja, usando os métodos o myzap de envio e recebimento de mensagens  sendo o recebimento via webhook, e mandando a mensagem pro chat.
Alguém tem alguma sugestão?

**Comment by jhowbhz** [comment]
Veja só irmão., talvez não seja dificil jogar isso em um Laravel e fazer um chat, saca só o video.

https://www.youtube.com/watch?v=uz-WaBcBpTg&ab_channel=APIGr%C3%A1tis

**Comment by jhowbhz** [comment]
Vou fechar essa issue, por não ter relação com o um problema ou bug, 

saudações!
