### ISSUE TITLE
QR Code não gera em SSL

### ISSUE THREAD

**Issue by poweriguana** [billbarsch/myzap#189]
Após executar a instalação completa e aplicar os direcionamentos via NGNIX, quando tenta conectar pela rota /start via SSL (https://{host}/start) o QR Code do frontend não é retornado

Pelo SSH o QR Code é gerado corretamente. 

http://{host}:{porta}/start Gera o QR Code corretamente

**Comment by jhowbhz** [comment]
verifique o seu arquivo .env

**Comment by poweriguana** [comment]
> verifique o seu arquivo .env

Pode ser um pouco mais específico, por favor?

**Comment by jhowbhz** [comment]
Verifique essa linha.

https://github.com/billbarsch/myzap/blob/3c55a3951e63855520be2327207052d93daed62a/.env_exemplo#L28

**Comment by poweriguana** [comment]
> Verifique essa linha.
> 
> https://github.com/billbarsch/myzap/blob/3c55a3951e63855520be2327207052d93daed62a/.env_exemplo#L28

Está configurado conforme documentação: 

`DOMAIN_SSL = myzap.meudominio.com.br`

**Comment by jhowbhz** [comment]
Coloca assim

```DOMAIN_SSL = https://myzap.meudominio.com.br```

**Comment by poweriguana** [comment]
> Coloca assim
> 
> `DOMAIN_SSL = https://myzap.meudominio.com.br`

Ainda o mesmo resultado. Sem retorno no frontend.

**Comment by as-schug** [comment]
O meu está assim, em um arquivos /etc/nginx/sites-enabled/whatsapp.conf
no .env, está

HOST=http://127.0.0.1:3333
DOMAIN_SSL=
HTTPS=0

Veja se consegue te ajudar em algo...


---------
- arquivo /etc/nginx/sites-enabled/whatsapp.conf

---------
server {
    listen 3334 ssl;
    server_name whatsapp.seudomini.com.br; #por exemplo

    include /etc/nginx/mynode/mynode_ssl_params.conf;
    include /etc/nginx/mynode/terasoft_ssl_cert_key.conf;

    access_log /var/log/nginx/whatsapp_access.log;
    error_log /var/log/nginx/whatsapp_error.log;

    location / {
        proxy_pass http://192.168.0.4:3333;

        include /etc/nginx/mynode/mynode_ssl_proxy_params.conf;
    }

}
---------
- arquivo /etc/nginx/mynode/mynode_ssl_params.conf 
---------
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;

ssl_ciphers 'TLS13+AESGCM+AES128:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';

ssl_session_cache shared:SSL:50m;
ssl_session_timeout 1d;
ssl_session_tickets off;
ssl_ecdh_curve X25519:sect571r1:secp521r1:secp384r1;

add_header Strict-Transport-Security "max-age=31536000";

ssl_dhparam /etc/ssl/certs/dhparam.pem;

---------
- arquivo /etc/nginx/mynode/terasoft_ssl_cert_key.conf
---------
ssl_certificate /etc/letsencrypt/live/seudomincio.com.br/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/seudominio.com.br/privkey.pem;

---------
- arquivo /etc/nginx/mynode/mynode_ssl_proxy_params.conf
---------
proxy_redirect off;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
