### ISSUE TITLE
Erro @c.us

### ISSUE THREAD

**Issue by iamedusm** [billbarsch/myzap#19]
sempre que tento fazer um envio de mensagem de texto ele me retorna esse erro, como consigo corrigir isso?
UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: wid error: invalid wid: @c.us

**Comment by AlanMartines** [comment]
Teria como você postar o trecho dessa parte do código, pode ser algum detalhe que esta passando batido.

**Comment by luizfeer** [comment]
> Teria como você postar o trecho dessa parte do código, pode ser algum detalhe que esta passando batido, o venom esta atualizado ?

Alan to usando seu pull de base, sabe pq as vezes fica starting e demora?

**Comment by AlanMartines** [comment]
Pra mim também fica assim as vezes, o eu faço é excluir o token ai resolve....

**Comment by luizfeer** [comment]
> Pra mim também fica assim as vezes, o eu faço é excluir o token ai resolve com novo pareamento, não tive tempo de verificar essa situação ainda...

quando deleto o token e pareio fica PAIRING :/

**Comment by AlanMartines** [comment]
me manda um print do console com retorno dos eventos, fazendo favor...

**Comment by luizfeer** [comment]
> me manda um print do console com retorno dos eventos, fazendo favor...

tem algum contato man? Telegram ou algo do tipo

**Comment by AlanMartines** [comment]
Whats e Telegram

**Comment by AlanMartines** [comment]
Qual seu email?

**Comment by luizfeer** [comment]
luiz.garra@live.com

**Comment by misterxis** [comment]
> 
> 
> > Pra mim também fica assim as vezes, o eu faço é excluir o token ai resolve com novo pareamento, não tive tempo de verificar essa situação ainda...
> 
> quando deleto o token e pareio fica PAIRING :/

coloquei o server em background pelo pm2, porem nao entra em PAIRING nem CONNECTED

**Comment by erickythierry** [comment]
@c.us é a identificação de usuarios
se o numero do celular é 55 11 9 11223344
então o id desse usuário no sistema do whatsapp vai ser 5511911223344@c.us
ja pra grupos é @g.us

tenho um bot pra whatsapp funcionando (so que em python) e ele utiliza a mesma base de funcionamento desse projeto aqui
