### ISSUE TITLE
Não recebe request externa

### ISSUE THREAD

**Issue by diogofm7** [billbarsch/myzap#192]
Fiz toda a instalação, sem erros configurei o IP da vps...

de dentro da vps se eu fizer um curl http://localhost:3333 ele me retorna o html certinho... 

mas se faço externo ou ate msm da vps, curl http://IP_VPS:3333 não funciona, da timeout...

subi um docker nessa mesma porta 3333, e consegui acessar, oq significa que não tenho nenhum bloqueio nessa porta na vps...

Outra duvida, existe a possibilidade de executar essa api com docker?? o docker-compose e o dockerfile desse repositório, estão prontos para serem usados??

**Comment by jhowbhz** [comment]
Como você fez o redirecionamento do externo pra dentro do Docker?
