### ISSUE TITLE
Venom não grava sessão no Firebase

### ISSUE THREAD

**Issue by matheusverri** [billbarsch/myzap#195]
Boa tarde! Estou com problemas para estabelecer a sessão utilizando a engine 3 (Venom) e gostaria de saber se alguém consegue me ajudar, por favor.

Após todas as instalações e configurações, iniciei o index.js via pm2 e fiz uma requisição para o /start. No "pm2 log index", após alguns instantes, recebo o QRcode, escaneio pelo celular com sucesso e entendo que deveria funcionar.
Quando tento fazer qualquer outra requisição como: sendText, SessionState, SessionConnect etc. recebo a mensagem: "A sessão do WhatsApp informada não está ativa."

Quando confiro o Firebase, não tenho nenhuma sessão gravada. Alguém conseguiria me ajudar?

OBS: a engine wppconnect está funcionando normalmente. O problema está acontecendo com a Venom.

**Comment by vazjunior** [comment]
Também estou com esse problema! Alguma solução?

**Comment by matheusverri** [comment]
Ainda não. Caso encontre algo que possa ajudar, compartilhe com a gente, por favor!
