### ISSUE TITLE
Documentação Postman & Examples

### ISSUE THREAD

**Issue by cirinho** [billbarsch/myzap#197]
No README tem um link para documentação `https://documenter.getpostman.com/view/11074732/UVkqrZtZ`, porém o link está quebrado com a seguinte mensagem de erro: `404 We couldn't locate the resource you're looking for. It may have been deleted.`

'''
![image](https://user-images.githubusercontent.com/3154405/214186165-62064898-a240-483e-932f-23f5a61abee5.png)
'''

Seria importante a documentação.

**Comment by renatoReboucas** [comment]
Estava indo abrir uma issue sobre isso agorinha mesmo 😅

**Comment by gabrieligbastos** [comment]
+1

**Comment by andrenogueiragbi** [comment]
Verdade, alguém que usa teria o documentação para import (postman ou insomnia)? Manda o link pra gente pfv  😉!

**Comment by jhowbhz** [comment]
Eu acabei de fazer um commit com a doc .json do postman, so importar.
