### ISSUE TITLE
Tenho interesse em unir os projetos e trabalharmos juntos

### ISSUE THREAD

**Issue by joaosouz4dev** [billbarsch/myzap#2]
https://github.com/joaosouz4/express-zapapi
Segue repo para analise.

**Comment by billbarsch** [comment]
alo joao, a união é sempre a melhor opção, todos saem ganhando, só não sei como eu poderia ajudar, confesso que esse é meu primeiro projeto node. não entendo quase nada da liguagem, tudo que eu fiz até agora é tudo que eu entendo de node kk uma linha a mais e eu fico totalmente perdido, olhei seu codigo não entendi nada kkkkkk

**Comment by joaosouz4** [comment]
@billbarsch também estou iniciando, podemos conversar mais e unir os projetos, assim podemos trabalhar juntos para criar essa api, consegui recentemente fazer mult sessoes podendo em uma mesma instância ter mais de um número, estou trabalhando com socket io, para o realtime

**Comment by tiagooliveira1** [comment]
@joaosouz4 você retirou seu projeto do ar? Está dando 404 aqui.

**Comment by billbarsch** [comment]
@joaosouz4 
a princípio eu ia usar apenas http normal mesmo, pois a api vai ser consumida por sistemas que não tem realtime tipo PHP e DELPHI, mas a questão do socket é interessante também, só não sei se conseguimos fazer os dois no mesmo projeto sem confundir muito as funcionalidades. o se projeto estava otimo para o socket, não deveria ter tirado do ar
