### ISSUE TITLE
WAPI is not defined

### ISSUE THREAD

**Issue by misterxis** [billbarsch/myzap#23]
I can read the QRCode, however this message appears in console and do not accept POST commands

```
new qrcode updated - session.state: QRCODE
- Compilation Mutation
- Compilation Mutation
- Injecting Sibionte...
(node:25468) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:5:29)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:6:27)
    at onRaf (__puppeteer_evaluation_script__:49:35)
    at pollRaf (__puppeteer_evaluation_script__:42:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:22)
    at ExecutionContext._evaluateInternal (/home/ubuntu/myzap/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/ubuntu/myzap/node_modules/puppeteer/lib/helper.js:94:19)
    at WaitTask.rerun (/home/ubuntu/myzap/node_modules/puppeteer/lib/DOMWorld.js:404:71)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
new qrcode updated - session.state: QRCODE
```

**Comment by doctorsanches** [comment]
Alguma novidade neste sentido? Estou com o mesmo problema!

**Comment by misterxis** [comment]
> 
> 
> Alguma novidade neste sentido? Estou com o mesmo problema!

Sim...

no diretorio da aplicacao, atualiza o venom
npm remove venom-bot
npm i --save venom-bot

**Comment by doctorsanches** [comment]
Muito bom @misterxis !!
obrigado!
Agora pareou 100%.

Infelizmente me deparei com um novo problema.

Ao enviar uma mensagem aparece o seguinte erro:

TypeError: client.sendMessageToId is not a function

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

session.state: PAIRING
session.state: CONNECTED
starting...session2
session.state: CONNECTED
(node:6269) UnhandledPromiseRejectionWarning: TypeError: client.sendMessageToId is not a function
    at session.client.then (/home/dottatec/myzap/sessions.js:200:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)

**Comment by misterxis** [comment]
> 
> 
> Muito bom @misterxis !!
> obrigado!
> Agora pareou 100%.
> 
> Infelizmente me deparei com um novo problema.
> 
> Ao enviar uma mensagem aparece o seguinte erro:
> 
> TypeError: client.sendMessageToId is not a function
> 
> > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >
> 
> session.state: PAIRING
> session.state: CONNECTED
> starting...session2
> session.state: CONNECTED
> (node:6269) UnhandledPromiseRejectionWarning: TypeError: client.sendMessageToId is not a function
> at session.client.then (/home/dottatec/myzap/sessions.js:200:41)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:6269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)

https://github.com/billbarsch/myzap/issues/15
