### ISSUE TITLE
Algum endpoint para confirmar se o qrcode foi lido ?

### ISSUE THREAD

**Issue by marciodiasdeveloper** [billbarsch/myzap#24]
Existe algum endpoint para confirmar caso o qrcode seja lido? alguma maneira de testar ou devo criar este endpoint?

**Comment by riberman** [comment]
Na mesma URL que você faz start na sessão, após ler o código QR, os status da sessão são alterados quando /start?sessionName=session1 retornar status CONNECTED no json significa que o QR foi lido e aparentemente está tudo bem para utilizar as funções de seu WhatsApp...
Uma forma simples é enquanto o QR não foi lido efetuar um loop URL do start até verificar que o código foi lido com sucesso para então parar o loop.

**Comment by AlanMartines** [comment]
isso mesmo, como  @riberman informou...
