### ISSUE TITLE
Erro ao enviar mensagem

### ISSUE THREAD

**Issue by marciodiasdeveloper** [billbarsch/myzap#25]
{
  "result": "error",
  "message": "QRCODE"
}

mesmo sendo feito a leitura do QRCode e passando o sessionName no método sendText

**Comment by AlanMartines** [comment]
Verificar se o nome da sessão está sendo repassado para o venom-bot corretamente...

**Comment by marciodiasdeveloper** [comment]
var session = Sessions.getSession(sessionName); está retornando false ... mas o nome da sessão está ok.

**Comment by marciodiasdeveloper** [comment]
new qrcode updated - session.state: QRCODE
session.state: OPENING
session.state: PAIRING
session.state: CONNECTED

agora foi ... não sei o q rolou tem hora que o state fica em QRCODE apenas e não fica CONNECTED.
