### ISSUE TITLE
Não envia mensagem, gera erro, alguem pode ajudar?

### ISSUE THREAD

**Issue by lepokoloko** [billbarsch/myzap#27]
Erro ao tentar enviar uma mensagem simples

(node:1333) UnhandledPromiseRejectionWarning: TypeError: client.sendMessageToId is not a function
    at session.client.then (/home/leandro/myzap/sessions.js:200:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by AlanMartines** [comment]
Bom dia, faz o seguinte, atualiza as dependência para as versões mais atual principalmente do puppeteer...

**Comment by lepokoloko** [comment]
Consegui resolver, o código aqui para enviar mensagem de texto no sessions.js está assim "
client.sendMessageToId " troquei para client.sendText e deu certo

**Comment by AlanMartines** [comment]
Da uma olha nesse projeto que estou trabalhando, tá de vagar mas tá indo [mywhats](https://github.com/AlanMartines/mywhats), talvez te ajude em problemas futuros...
