### ISSUE TITLE
tem hora que o state fica em QRCODE apenas e não fica CONNECTED.

### ISSUE THREAD

**Issue by lepokoloko** [billbarsch/myzap#28]
Direto acontece isso, porém habilitando os logs das mensagens recebidas, aparece as informações recebidas, ou seja, na realidade já está conectado porém o status fica travado como QRCODE, alguém já passou por isso e conseguiu resolver de alguma forma ?

**Comment by marciodiasdeveloper** [comment]
se descobrir me fale. rsrsrs .... passando por isso aqui .... tenho que dar sorte para ficar CONNECTED.

**Comment by lepokoloko** [comment]
Consegui deixar funcional, porem as vezes nao fica connected, alterei o session,js
as funcoes que sao responsaveis para enviar mensagens


deixei assim 

 static async sendText(sessionName, number, text) {
        var session = Sessions.getSession(sessionName);
        if (session) {

// antes só tinha o connected, dessa forma consigo enviar mensagem normalmente agora 
            if (session.state == "CONNECTED" || session.state == "QRCODE" || session.status == "isLogged") {
                var resultSendText = await session.client.then(async client => {
                    return await client.sendText(number + '@c.us', text);
                });
                return { result: "success" }
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUNDSENDTXT" };
        }
    }//message

**Comment by lepokoloko** [comment]
@oliveiraLuan chama la no whatsapp 15 996213328 ai te ajudo
