### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by aulianza** [billbarsch/myzap#3]
![image](https://user-images.githubusercontent.com/15605885/88476379-138d6680-cf62-11ea-945f-95d4931f3879.png)

hello sir, i was scan the qr code on my whatsapp web, after that, in the terminal said token saved successfully, but after countdown "starting 59", client.close - session.state: CLOSED, what step that i miss?

**Comment by aulianza** [comment]
cannot sent message to unknown user, how to solve it?

**Comment by billbarsch** [comment]
hello @aulianza  it's a problem with venon (another project we work with) unfortunately some times it is not connecting to whatsapp, I have same problem here
