### ISSUE TITLE
tentei instalar e rodar o projeto mas nao faz scan do QRcode

### ISSUE THREAD

**Issue by erickythierry** [billbarsch/myzap#31]
nao manjo de js, mas entendo um pouco de linux. a meu ver está tudo rodando normalmente. mas ao tentar fazer scan do qr code usando a chamada:
http://localhost:3333/qrcode?sessionName=session1&image=true

acaba nao escaneando. nao da mensagem de erro nenhuma no whatsapp do celular. simplesmente não escaneia.

alguém com o mesmo problema?

**Comment by evertonfraagae** [comment]
Tbm estava com o mesmo problema. Eu consegui autenticar salvando a imagem do qrcode como imagem e depois eu fiz o escaneamento com o whatsapp. Mas tem que ser rápido

**Comment by erickythierry** [comment]
> Tbm estava com o mesmo problema. Eu consegui autenticar salvando a imagem do qrcode como imagem e depois eu fiz o escaneamento com o whatsapp. Mas tem que ser rápido

consegui resolver. era uma besteira. a imagem do qrcode gerada pelo script nao tem fundo, então se tentar fazer scan com um fundo diferente do padrão o whatsapp nao identifica. coloquei num fundo branco e foi de boas
