### ISSUE TITLE
Cannot GET /message

### ISSUE THREAD

**Issue by narlles** [billbarsch/myzap#34]
Quando tento enviar qualquer menssagem com a variavel message?number=55***********&message=oi, recebo a mesagem Cannot GET /message

**Comment by Advansoftware** [comment]
eu tbm tentei rodar essa rota, aparentemente parece que a rota esta sendo "sendText" via post, mas não tenho certeza ainda....

**Comment by taknamecom** [comment]
I have this problem too.
I can not send GET request to send msg! 

Cannot GET /message

**Comment by LyoRepo** [comment]
> I have this problem too.
> I can not send GET request to send msg!
> 
> Cannot GET /message

+1

**Comment by thiagoiwanko** [comment]
mesmo problema, acho que não manda mais msg como no video pela linha html
