### ISSUE TITLE
Multiplos numeros

### ISSUE THREAD

**Issue by misterxis** [billbarsch/myzap#37]
Como eu poderia enviar para mais de um numero dentro do sendFile. Quero passar um array de numeros e disparar.
Gostaria de efetuar um client.sendFile multiplo dentro do metodo. Alguem pode ajudar?

```
static async sendFile(sessionName, number, filePath, fileName, caption) {
        var session = Sessions.getSession(sessionName);
        if (session) {
            if (session.state == "CONNECTED") {
                var resultSendFile = await session.client.then(async (client) => {
                    console.log(filePath);
                    return await client.sendFile(number + '@c.us', filePath, fileName, caption);
                });//client.then(
                return { result: "success" };
            } else {
                return { result: "error", message: session.state };
            }
        } else {
            return { result: "error", message: "NOTFOUND" };
        }
    }
```

**Comment by romulloleal** [comment]
Você pode fazer um map do array e dentro do map colocar o client.sendFile
algo como:

`numeros.map(numero => {
    return await client.sendFile(numero+ '@c.us', filePath, fileName, caption);
})`

Mas já deixo avisado que isso pode dar ban pois vai ser disparo em massa e o whatsapp não gosta disso

**Comment by romulloleal** [comment]
> @misterxis conseguiu resolver, estou com a mesma necessidade e talvez posso ajudar... @romulloleal você saberia dizer qual seria o limite pra evitar o ban? Tenho um grande receio de a minha necessidade causar isso...

Não sei qual o limite @ribeiroevandro mas aconselho a comprar um chip para testes para ver o limite.
