### ISSUE TITLE
Quando chama a rota do qrcode erro

### ISSUE THREAD

**Issue by danicampos01** [billbarsch/myzap#4]
Amigo passando por um erro aqui

a rota de start está ok! o venom sobe fica atualizando a qrcode.
masquando chamo a rota:
http://localhost:3001/qrcode?sessionName=minhasessao&image=true

tá passando por isso ai não? se passou puder me da um ajuda! valeu

(node:1) UnhandledPromiseRejectionWarning: ReferenceError: qrcodeResult is not defined
node-myzap    |     at app.get (/index.js:45:17)
node-myzap    |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
node-myzap    |     at next (/node_modules/express/lib/router/route.js:137:13)
node-myzap    |     at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
node-myzap    |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
node-myzap    |     at /node_modules/express/lib/router/index.js:281:22
node-myzap    |     at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
node-myzap    |     at next (/node_modules/express/lib/router/index.js:275:10)
node-myzap    |     at jsonParser (/node_modules/body-parser/lib/types/json.js:110:7)
node-myzap    |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
node-myzap    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
node-myzap    | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by billbarsch** [comment]
acabei de corrigir, tenta agora tinha bug mesmo kk

**Comment by danicampos01** [comment]
(node:1) UnhandledPromiseRejectionWarning: TypeError: session.qrcode.replace is not a function
node-myzap    |     at app.get (/usr/src/app/index.js:45:49)
node-myzap    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
node-myzap    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
node-myzap    |     at Route.dispatch (/usr/src/app/node_modules/express/lib/r
