### ISSUE TITLE
Erro durante instalação

### ISSUE THREAD

**Issue by ikarofsouza** [billbarsch/myzap#44]
Faço a instalação, mas ao chegar no passo ( npm install  ) apresenta o seguinte erro:

> node install.js

Downloading Chromium r818858 - 132.1 Mb [====================] 100% 0.0s
Chromium (818858) downloaded to /root/myzap/node_modules/puppeteer/.local-chromium/linux-818858
npm WARN myzap@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

E após isso, se executar o ( node index.js) trava na mensagem abaixo:

Http server running on port 3333

Como posso resolver?

**Comment by Advansoftware** [comment]
Http server running on port 3333 é porque seu servidor esta rodando normalmente na porta 3333.

pra acessar tenta colocar  http://localhost:3333 se estiver usando em seu computador local, possivelmente vai aparecer um erro dizendo "Cannot GET /" é porque você não passou os dados via post para a url do seu servidor. então tenta iniciar a sessão colocando "http://localhost:3333/start?sessionName=session1" e veja o que retorna, após rodar o projeto usando "node index.js"
