### ISSUE TITLE
QRCODE como false

### ISSUE THREAD

**Issue by Jaderberto** [billbarsch/myzap#45]
Boa tarde amigos.

Ao iniciar a sessão, o retorno é CONNECTED.

Ao buscar o QRCODE, o retorno é false

Alguém está passando por isso? Sabem como me ajudar?

{
  "result": "success",
  "message": "CONNECTED",
  "qrcode": false
}

**Comment by danielpinon** [comment]
Já foi resolvido na atualização do Venom!

**Comment by Sulivan1999** [comment]
Olá. Eu ainda continuo recebendo a mesma coisa do @Jaderberto.

Depois de iniciado a sessão e buscar o QrCode o retorno é false. Alguém pode me ajudar, por favor?

**Comment by Jaderberto** [comment]
O Connect Zap é uma interface que possibilita que seu sistema envie mensagens, imagens e documentos para usuários do whatsapp.
Com essa ferramenta, é possível realizar diversas automações no processo de cada empresa como os exemplos abaixo:
• Envio de boleto bancário para clientes com notificações sobre vencimento.
• Envio de solicitação de aprovação para determinado processo como: Solicitação de Compras, Pedido de Compras, Cotação, Contratos, etc.
• Envio de Nota Fiscal de Saída para clientes.
• Envio de contra-cheque para funcionários.
• Comunicação do RH com Funcionários.
• Notificações diversas, como saldo em estoque, não conformidades, procedimentos de segurança, servidor com baixa memória, etc.

www.connectzap.com.br
