### ISSUE TITLE
WhatsappWeb em pararelo com o venom

### ISSUE THREAD

**Issue by lepokoloko** [billbarsch/myzap#47]
Existe a possibilidade de rodar sessoes no whatsapp web e outra pelo venom, quando tenta abrir whatsappweb, derruba o venom, alguem sabe alguma solucao ?

**Comment by joaosouz4dev** [comment]
Ainda não existe, é a mesma coisa de abrir dois whatsapp web. Só terá como quando o whatsapp liberar essa funcionalidade
