### ISSUE TITLE
Problema após instalação da ultima versão do projeto

### ISSUE THREAD

**Issue by doctorsanches** [billbarsch/myzap#48]
Alguem sabe o motivo da excessão ao iniciar uma nova sessão?
Comecou a ocorter após atualização do projeto.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
session == false
newSession.state: STARTING
(node:8501) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/downloads/myzap/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/downloads/myzap/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/downloads/myzap/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8501) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/downloads/myzap/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/downloads/myzap/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/downloads/myzap/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by Jaderberto** [comment]
Estou tendo o mesmo problema.

**Comment by ailtonpm** [comment]
Eu tb. Sem essas linhas inicia, mostra o qr code mas não passa do qr code.
            jsonbinio_secret_key: process.env.JSONBINIO_SECRET_KEY,
            jsonbinio_bin_id: process.env.JSONBINIO_BIN_ID

**Comment by Soberano0** [comment]
Estou com o mesmo problema

**Comment by Jaderberto** [comment]
No meu caso, quando tento iniciar a sessão, o status fica como STARTING eternamente.

**Comment by tqi-mvilela** [comment]
Estou com o mesmo probleam

**Comment by mauriciovilela** [comment]
Pessoal consegui resolver e funcionou:

1) Atualize o venom para a última versão (3.0.6)
2) Utilize o QR CODE do terminal
![image](https://user-images.githubusercontent.com/4934675/109839289-bbb88b80-7c25-11eb-8f10-f333fe10fd31.png)

**Comment by Jaderberto** [comment]
Amigo obrigado pela dica.

Desculpe a ignorancia da pergunta, mas sabe me dizer o comando para atualizar o venon?

**Comment by Soberano0** [comment]
Desculpa a pergunta, mas sou iniciante, qual arquivo que faço essas alterações e qual o comando para atualizar o venom?

**Comment by mauriciovilela** [comment]
> Desculpe a ignorancia da pergunta, mas sabe me dizer o comando para atualizar o venon?

Opa tranquilo amigo.

A alteração deve ser feita no arquivo "package.json"

**Comment by L1T3** [comment]
Amigao nao consigo dar o yarn install retorna que nao existe install e onde edito o codigo que voce mandou? obgd

**Comment by Jaderberto** [comment]
O Meu package.json está assim. Seria aqui mesmo?

![image](https://user-images.githubusercontent.com/35386787/109846178-b01c9300-7c2c-11eb-80b3-9d0786cc6ebc.png)

**Comment by ikarofsouza** [comment]
> O Meu package.json está assim. Seria aqui mesmo?
> 
> ![image](https://user-images.githubusercontent.com/35386787/109846178-b01c9300-7c2c-11eb-80b3-9d0786cc6ebc.png)

{
    "name": "myzap",
    "version": "1.0.0",
    "description": "Free OpenSource Whatsapp Api",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "Bill Barsch",
    "license": "ISC",
    "dependencies": {
        "axios": "^0.21.1",
        "cors": "^2.8.5",
        "dotenv": "^8.2.0",
        "express": "^4.17.1",
        "mime": "^2.4.6",
        "venom-bot": "^3.0.8"
    }
}

**Comment by mauriciovilela** [comment]
> Amigao nao consigo dar o yarn install retorna que nao existe install e onde edito o codigo que voce mandou? obgd

Você tem que instalar o yarn `npm install -g yarn`

**Comment by mauriciovilela** [comment]
> > O Meu package.json está assim. Seria aqui mesmo?
> > ![image](https://user-images.githubusercontent.com/35386787/109846178-b01c9300-7c2c-11eb-80b3-9d0786cc6ebc.png)
> 
> {
> "name": "myzap",
> "version": "1.0.0",
> "description": "Free OpenSource Whatsapp Api",
> "main": "index.js",
> "scripts": {
> "test": "echo "Error: no test specified" && exit 1"
> },
> "author": "Bill Barsch",
> "license": "ISC",
> "dependencies": {
> "axios": "^0.21.1",
> "cors": "^2.8.5",
> "dotenv": "^8.2.0",
> "express": "^4.17.1",
> "mime": "^2.4.6",
> "venom-bot": "^3.0.8"
> }
> }

Isso mesmo

**Comment by L1T3** [comment]
certo e o codigo q vc disse para modificarmos onde é?

**Comment by Soberano0** [comment]
Fiz exatamente isso, quando uso o node index.js, ele não abre o qr, como faço para acessar? pois agora o qrcode?sessionName=session1&image=true fica como not found

**Comment by L1T3** [comment]
@mauriciovilela desculpa insistir mas nao sei onde edita o codigo q disse estou precisando mt da api

**Comment by Soberano0** [comment]
@L1T3 package.json

**Comment by Soberano0** [comment]
@L1T3 e o outro session.js

**Comment by Soberano0** [comment]
sessions*

**Comment by mauriciovilela** [comment]
@Soberano0 no arquivo `session.js` encontre o trecho abaixo e faça a alteração
https://user-images.githubusercontent.com/4934675/109839289-bbb88b80-7c25-11eb-8f10-f333fe10fd31.png

**Comment by Soberano0** [comment]
@Soberano0 já fiz essa alteração, após isso é usar o node index.js certo? Porém ele só carrega a porta e não mostra o QR

**Comment by ikarofsouza** [comment]
> @Soberano0 no arquivo `session.js` encontre o trecho abaixo e faça a alteração
> https://user-images.githubusercontent.com/4934675/109839289-bbb88b80-7c25-11eb-8f10-f333fe10fd31.png

Qual linha?

**Comment by L1T3** [comment]
depois de todas alterações continua mesmo erro UnhandledPromiseRejectionWarning: Error: Request failed with status code 404

**Comment by Soberano0** [comment]
Aqui também, quando tento acessar start?sessionName=session1&image=true, só se for um caminho diferente

**Comment by ikarofsouza** [comment]
A API tem muito tempo que não é atualizada, na ultima semana teve atualizações grandes no Venom, provavelmente esse é o problema.

**Comment by L1T3** [comment]
![image](https://user-images.githubusercontent.com/22354740/109849796-b1a88400-7c49-11eb-975d-669ef0c53932.png)

**Comment by ikarofsouza** [comment]
Realizei as atualizações, mas após instalar apresenta:

Http server running on port undefined

**Comment by Soberano0** [comment]
Abre a porta 3333, se for virtual box só liberar lá

**Comment by Soberano0** [comment]
@mauriciovilela para o QRCode aparecer você só usou node index.js e ele apareceu no console? Ou tem algum lugar especifico?

**Comment by ikarofsouza** [comment]
> Realizei as atualizações, mas após instalar apresenta:
> 
> Http server running on port undefined

Corrigi repetindo o código: cp .env-example .env

**Comment by Jaderberto** [comment]
O meu inicia assim:

Mas fica direto como STARTING

![image](https://user-images.githubusercontent.com/35386787/109850883-c4af5a00-7c31-11eb-8015-faf8ed66a5d3.png)

**Comment by ikarofsouza** [comment]
Pelo que percebi o problema esta logo ao iniciar a seção (/start?sessionName=session1)

![Sem Título](https://user-images.githubusercontent.com/48399495/109852399-a60a8c80-7c4c-11eb-9d6c-98b470612e73.png)

**Comment by Soberano0** [comment]
Cara, se eu não me engano não tinha erro ao startar, pode ter sido devido as alterações.

**Comment by ikarofsouza** [comment]
Já estava antes, fiz o teste sem as alterações citadas aqui, e o erro permanece.

> Cara, se eu não me engano não tinha erro ao startar, pode ter sido devido as alterações.

**Comment by mauriciovilela** [comment]
@Soberano0 @ikarofsouza @Jaderberto Fiz um fork e depois algumas mudanças pra funcionar na última versão
https://github.com/mauriciovilela/node-zap

**Comment by Jaderberto** [comment]
Obrigado @mauriciovilela  consegui utilizar do seu código e estou na última versão.

Porém, ele não consegue iniciar a sessão pra gerar o QRCODE, fica parado nessa linha:
 [instance: session1]: Checking is logged...

![image](https://user-images.githubusercontent.com/35386787/109859276-861e9d00-7c3b-11eb-992c-3457d99b0edc.png)

**Comment by mauriciovilela** [comment]
Tem uma nova versão faz o "clone" de novo

**Comment by Jaderberto** [comment]
Agora está aparecendo o seguinte erro ao no /start


(node:2967) UnhandledPromiseRejectionWarning: Error no open browser....
(node:2967) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2967) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not ha
ndled will terminate the Node.js process with a non-zero exit code.

**Comment by mauriciovilela** [comment]
> Agora está aparecendo o seguinte erro ao no /start
> 
> (node:2967) UnhandledPromiseRejectionWarning: Error no open browser....
> (node:2967) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
> unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:2967) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not ha
> ndled will terminate the Node.js process with a non-zero exit code.
Fiz uma atualização faz o "clone" de novo

**Comment by Jaderberto** [comment]
@mauriciovilela muito obrigado. Funcionou aqui. Foi só eu rodar o comando:

sudo apt install -y curl nano gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget build-essential apt-transport-https libgbm-dev

**Comment by mauriciovilela** [comment]
Top

Em qua., 3 de mar. de 2021 16:41, Jaderberto <notifications@github.com>
escreveu:

**Comment by Jaderberto** [comment]
Pessoal, eu criei um grupo no Whatsapp para discutirmos a api.

Seria legal que todos participassem.

https://chat.whatsapp.com/K0PJFJkjrenByDQmmQ1yaz
