### ISSUE TITLE
instalação nova...erro ao iniciar o projeto.

### ISSUE THREAD

**Issue by thiagotoneli** [billbarsch/myzap#50]
"Fiz a instalação do zero e execultei o node index.js...apos 

resultado:

root@taj:/home/taj/myzap# node index.js
Http server running on port 3000

![image](https://user-images.githubusercontent.com/80266445/110689471-7960f280-81c1-11eb-9034-48bee0e39b6a.png)

Apos isso fui no browser e coloquei 

http://localhost:3000/start?sessionName=session1

resultado:

For more info visit: https://github.com/orkestral/venom/blob/master/Update.md

- There is a new version available
- Waiting... checking the browser...
- There is a new version available
- Error no open browser....
(node:12608) UnhandledPromiseRejectionWarning: Error no open browser....
(node:12608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![image](https://user-images.githubusercontent.com/80266445/110689558-939ad080-81c1-11eb-9559-37d0e1d62089.png)

Sou leigo no assunto mas acho que deu erro alguem pode me ajudar?

**Comment by Advansoftware** [comment]
Tenta rodar "npm update venom-bot"  depois da uma atualizada na versão do seu node.js....
depois q fizer tudo, tenta rodar e me diz o que deu! valeu u.u pra mim com tudo atualizado está tranquilo....
mas detalhe isso é só um aviso, não um erro, ou seja, o seu servidor esta rodando, eu preciso saber como esta seu ambiente, parece q vc esta rodando em um servidor externo, recomendo vc colocar o seguinte http://ip_do_seu_servidor:3000/start?sessionName=session1. 
- substituindo pelo ip do seu servidor.
- provavelmente na hora de gerar o qrcode, vc vai precisar substituir também o localhost pelo ip do seu servidor
- detalhe importante, para vc enviar mensagem deve ser pelo método POST, e não GET

**Comment by danielpinon** [comment]
Com essa nova atualização tente fazer o git pull, rm -rf node_modules, npm install e node index.js para testar se está funcionando! Se caso estiver feche a issue.
