### ISSUE TITLE
error al habilitar imágenes para qrcode

### ISSUE THREAD

**Issue by iqbaldal** [billbarsch/myzap#61]
por favor, cuando intento activar la imagen para obtener qrcode ocurre un error como este

![Screenshot_6](https://user-images.githubusercontent.com/82546403/114785809-6ab0c100-9da7-11eb-95ed-ad42cccf5e84.png)

**Comment by bgastaldi** [comment]
> por favor, cuando intento activar la imagen para obtener qrcode ocurre un error como este
> 
> ![Screenshot_6](https://user-images.githubusercontent.com/82546403/114785809-6ab0c100-9da7-11eb-95ed-ad42cccf5e84.png)

Atualiza seu venom:
npm update venom-bot

**Comment by jhowbhz** [comment]
Tenta o seguinte.

```
rm -R node_modules/
npm install --unsafe-perm
```

**Comment by alexishida** [comment]
remove myzap tokens

rm -fr myzap/tokens/*
