### ISSUE TITLE
Status STARTING não muda

### ISSUE THREAD

**Issue by htsnet** [billbarsch/myzap#62]
Tenho recebido a mensagem (algumas vezes) como STARTING, tanto na função de **start** como na de **status**. Já testei em localhost e em servidor cloud e ambos se comportam da mesma forma. Mesmo aguardando horas, a mensagem continua a mesma. 

Quando está nesta situação, o **qrcode** também retorna assim, não permitindo a conclusão do processo. 

Alguma dica de como resolver?

**Comment by RichardKBR** [comment]
Olá htsnet. Notei esse problema também. Descobri que ocorre quando usa o endpoint CLOSE. 
Depois de fazer um CLOSE, quando tenta dar START novamente fica sempre neste estado de "Starting". Tá parecendo um BUG, como se não tivesse finalizado a sessão direito. Pra vc poder continuar testando reinicia seu server ou troca de nome de sessão.

Outra coisa, não se se vc está usando o Venom ou WPPCONNECT. Para mim o Venom não funciona.... já tentei várias coisas.

**Comment by RichardKBR** [comment]
Na verdade eu só consegui usar com o wppconnect, com o venom nunca funcionou pra mim.

**Comment by htsnet** [comment]
@RichardKBR Fiz um procedimento e resolveu (pelo menos desta vez, não sei se é sempre): eu fui na pasta "tokens" e apaguei o json relativo à sessão que eu estava tendo problemas. A partir daí foi suave: fiz o start, qrcode e envio sem problemas. Continuei usando o Venom (não mudei).

**Comment by AlanMartines** [comment]
Sim, mas é paliativo... reinicia o serviço que vau bugar novamente
