### ISSUE TITLE
Grupo do WhatsApp está lotado! Favor abrir outro grupo!

### ISSUE THREAD

**Issue by feraamorim** [billbarsch/myzap#63]
Grupo do WhatsApp está lotado! Favor abrir outro grupo por favor!

**Comment by AdemirShark** [comment]
Cria no Telegram, pode ter mais usuarios

**Comment by MaxSuendre** [comment]
Quero participar do grupo também!!!
Seria ótimo o grupo no telegram!!

**Comment by AlanMartines** [comment]
Grupo criado pessoal 

https://t.me/joinchat/4coqGP7GwlYzYjg5
