### ISSUE TITLE
Capturar mensagem recebida, tem como?

### ISSUE THREAD

**Issue by feraamorim** [billbarsch/myzap#66]
Eu vi que no Venom tem pequeno exemplo, tem como fazer isso funcionar no myzap?

function start(client) {
  client.onMessage((message) => {
    if (message.body === 'Hi' && message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}

**Comment by AlanMartines** [comment]
Sim, você vai fazer as tratativas dentro da  função **client.onMessage((message)**
Conforme exemplo da lib
```js
client.onMessage((message) => {
if (message.body === 'Hi' && message.isGroupMsg === false) {
client.sendText(message.from, 'Welcome Venom 🕷').then((result) => {
console.log('Result: ', result); //return object success
});
```

No exemplo, toda vez que a Palavra **Hi** for enviada ele executa a ação de responder **Welcome Venom**, ai é so alterar para seu senário...

**Comment by jhowbhz** [comment]
Você pode ler essas informações no WebHook.

**Comment by hcbravin** [comment]
Poderia explicar melhor sobre isso? Gostaria de implementar só uma mensagem de aviso que envia um link para a pessoa descadastrar, caso ela queira. Mas, confesso que não entendi muito de programação.

**Comment by fredzolio** [comment]
Como eu leio essa informação em método GET?

**Comment by jhowbhz** [comment]
Nesse vídeo você pode ter uma ideia de como fazer isso.

https://www.youtube.com/watch?v=puM4BzLaNoQ&t=455s&ab_channel=APIGr%C3%A1tis
