### ISSUE TITLE
getAllChatsNewMsg não esta funcionando!

### ISSUE THREAD

**Issue by AdemirShark** [billbarsch/myzap#67]
Alguem poderia nos ajudar com essa questão?

getAllChatsNewMsg não funciona assim como não conseguimos resolver a questão de mensagens recebidas,

Grato

**Comment by phdorocha** [comment]
> Alguem poderia nos ajudar com essa questão?
> 
> getAllChatsNewMsg não funciona assim como não conseguimos resolver a questão de mensagens recebidas,
> 
> Grato

Para resolver esse problema das mensagens não lidas, basta trocar o parâmetro no arquivo index.js. Lá está req.body.sessionName, o correto é req.query.sessionName pois é um get.
