### ISSUE TITLE
ENVIAR AUDIO GRAVANDO DIRETAMENTE DO HTML

### ISSUE THREAD

**Issue by petryck** [billbarsch/myzap#7]
Estou com problemas para enviar audio, quando gravo o áudio no client side com javascript e converto ele para base64 quando envio para o servidor ele entende como documento, na teoria eu acredito que o problema seja na codificação do do formato quando faço a gravação do áudio na web, consegue me ajuda ?

**Comment by AlanMartines** [comment]
Qual a mensagem de retorno ?
