### ISSUE TITLE
Limitações

### ISSUE THREAD

**Issue by ribeiroevandro** [billbarsch/myzap#70]
Alguém saberia quais são as limitações nos envios do WhatsApp? Meu projeto tem uma demanda de pelo menos 250 mensagens por dia, basicamente irei enviar confirmações de agendamentos. Com isso, existe alguma forma de não tomar um `ban`?

**Comment by igormenin** [comment]
Nesse processo, o melhor seria no ato do agendamento, o paciente ou cliente já ter salvo o seu numero que irá interagir com ele. Prevenindo assim a possibilidade de ser denunciado como SPAM. O Cliente tendo salvo já terá um percentual grande de não ocorrer nenhum problema.
