### ISSUE TITLE
Envio de mensagens enquanto o celular estiver desconectado

### ISSUE THREAD

**Issue by francisbreit** [billbarsch/myzap#73]
Estou tentando criar uma maneira de enviar mensagens quando o celular foi pareado, mas foi temporariamente desconectado. Eu tentei com guzzlehttp, mas não tive sucesso. Seria uma espécie de fila para enviar mensagens quando o celular se reconectar.

**Comment by krelod** [comment]
Olá @francisbreit, excelente sujestão. Estou aguardando um pull request meu ser efetivado (ou não) para poder efetivar essas sujestões que estou encontrando.

**Comment by jhowbhz** [comment]
Já foi liberado essa pull request
