### ISSUE TITLE
Não está enviando msg para números Novos

### ISSUE THREAD

**Issue by carolpinn** [billbarsch/myzap#79]
De uns 3 dias pra cá, o bot parou de enviar msgs para números que não conhece.  Para os números que ele conhece, as msgs são enviadas normalmente, porém para desconhecido não.  Só depois que eu entro pelo aparelho e mando uma msg pelo próprio aparelho (o contato passa a ficar na lista), ele consegue enviar a msg.
Acredito que teve alguma atualização do whatsapp web. 

Alguém mais com esse problema?

**Comment by CeloGomesBR** [comment]
Eu estou com esse problema também.  Se alguém souber como resolver, por favor, poste aqui!!!

**Comment by carolpinn** [comment]
Uma pessoa comentou em outro post.  Parece que está com problemas mesmo.  @CeloGomesBR você conseguiu resolver?
