### ISSUE TITLE
Sugestão para remover /exec

### ISSUE THREAD

**Issue by alexishida** [billbarsch/myzap#81]
Bom dia,

Dou como sugestão a remoção desse comando /exec que em um server de produção da a possibilidade de executar comandos malicioso.

https://github.com/billbarsch/myzap/blob/3e909fbce755139bf382a202b70874ac12bf3e4b/index.js#L41

**Comment by krelod** [comment]
Bom dia amigo!
Já fiz essa sujestão e inclusive, no meu pull request chamado "implementando uma nova estrutura para o código" eu inseri um comentário.
Aguardaremos a próxima atualização desse projeto, pois a última foi em Abril.

**Comment by cooperrj** [comment]
Será que o nosso amigo vai lançar nova atualização com os pull requests enviados? A aplicação está com algumas falhas complicadas como não pegar as mensagens não lidas e envio de mensagens para novos contatos.

**Comment by phdorocha** [comment]
> Será que o nosso amigo vai lançar nova atualização com os pull requests enviados? A aplicação está com algumas falhas complicadas como não pegar as mensagens não lidas e envio de mensagens para novos contatos.
Para resolver esse problema das mensagens não lidas, basta trocar o parâmetro no arquivo index.js. Lá está req.body.sessionName, o correto é req.query.sessionName pois é um get.
