### ISSUE TITLE
Api Instalada mas não envia mensagem

### ISSUE THREAD

**Issue by allysson151** [billbarsch/myzap#84]
Gostaria de ajuda nessa questão.. acabei de instalar todas as dependências, está rodando tudo certo e aparece o status conectado... Mas quando envio uma mensagem aparece esse erro ai.. alguém poderia me ajuda?

![erroapi](https://user-images.githubusercontent.com/47985926/125802083-fc5c5002-dc53-4d59-acb4-c89ec26b40ba.PNG)

**Comment by LucasWPL** [comment]
Estou com o mesmo problema. Já reinstalei, mudei versão do linux e até agora nada.

**Comment by alexishida** [comment]
+1

**Comment by alexishida** [comment]
Eu corrigi o meu problema executando

$ npm update

Ps. To usando o Venom (https://github.com/orkestral/venom)

**Comment by keomati** [comment]
Em tese esse erro foi lucionado na nova versão do Venom. Porém se fizemos o update geram diversos outros erros.

**Comment by keomati** [comment]
Simples pessoal. No package.json só mudar a versão do venom-bot para 3.0.21 prontinho

**Comment by adiciusnada** [comment]
consegui resolver da seguinte forma...
os 2 procedimentos acima, 
alterei no arquivo package.json
        "venom-bot": "^3.0.21"
fechei a api e rodei um npm update
to rodando no venom...
