### ISSUE TITLE
Depois de um tempo parou de funcionar subtamente

### ISSUE THREAD

**Issue by falecomguilhermelima** [billbarsch/myzap#86]
Segui todos os passos e deixei o Myzap pronto e funcionando enquanto fazia outras modificações no sistema, quando fui subir para produção resolvi testar e vi que não estava funcionando, acessei a console e está aparecendo essa mensagem de erro:
![ErroMyzap](https://user-images.githubusercontent.com/57272052/126717396-cca55936-fcc5-4df9-bcfe-253364f21618.JPEG)
Estou precisando muito resolver isso pois o sistema já deveria estar em produção, obrigado!

**Comment by falecomguilhermelima** [comment]
O grupo do Whatsapp está lotado

**Comment by falecomguilhermelima** [comment]
Resolvi com um npm update e subi a sessão novamente, mas toda vez tenho que fazer isso?
De quanto em quanto tempo vai cair?

**Comment by fgouveia708** [comment]
@falecomguilhermelima encontrou a raiz do problema?

**Comment by falecomguilhermelima** [comment]
Não cara, fiz apenas o que comentei acima e voltou, estou testando de tempos em tempos pra ver se cai de novo, mas perdi a confiança, complicado...

**Comment by fgouveia708** [comment]
Estou executando a aplicação com Docker, porém toda vez que crio a imagem executo o NPM. No entanto, o **problema persiste**.

![image](https://user-images.githubusercontent.com/30754335/126834417-f7cd17f7-848b-4d60-a731-357ac1e9b918.png)

**Comment by jhowbhz** [comment]
Está usando a v1? ou a v2?

**Comment by AlanMartines** [comment]
Voce esta usando chrome ou chromium?

**Comment by guilhermedemacchi** [comment]
Hoje voltou a acontecer, mesma coisa, depois de um tempo para de funcionar.
Usei o Chrome e a versão é a v2

**Comment by jhowbhz** [comment]
Mas qual o problema? Manda um log ou print da API

**Comment by jhowbhz** [comment]
Sem novas interações?
