### ISSUE TITLE
Como fazer para salvar o QRCode de cada número que ira enviar?

### ISSUE THREAD

**Issue by tiagocaus** [billbarsch/myzap#89]
É possivel salvar o QRCode de cada numero que faz o envio? Caso sim, como fazer?

**Comment by jhowbhz** [comment]
sim, basta salvar o base64 que vem do webhook.

**Comment by AlanMartines** [comment]
@tiagocaus deu certo o que foi sugerido?

**Comment by lcava000** [comment]
How do I save the base64 that comes from the webook to save the qr code and avoid putting it every time?
