### ISSUE TITLE
Envio pela Url Helpp

### ISSUE THREAD

**Issue by rogerbbh** [billbarsch/myzap#90]
Tudo bem @billbarsch sera qeu voce poderia me dizer como faco o envio pela url, como voce fez no seu video no youtube
ja tentei 

http://133.50.141.51:3333/sendText?number=5531992244628&text=teste

http://133.50.141.51:3333/message?number5531992244628&messagen=Teste api

http://133.50.141.51:3333/sendText?number=5531992244628&text=teste

E nada me da esta ajuda ai por favor!

**Comment by CarlosNegrao** [comment]
Você teria que modificar o index. js para recer por get ao invés de post e trocar req.body por rec.query.
