### ISSUE TITLE
Criando uma AWS lambda

### ISSUE THREAD

**Issue by tiagocaus** [billbarsch/myzap#91]
É possível criar um AWS lambda para rodar esse código?

Caso sim, como deve ser feito?

Obrigado.

**Comment by rogerbbh** [comment]
oi me chma no whats 31 991244628

**Comment by rogerbbh** [comment]
oi @hostcia me chma no whats 31 991244628

**Comment by hostcia** [comment]
Bom dia @rogerbbh por gentileza, coloque seu valor aqui. Se eu gostar entro em contato. Obrigado.
