### ISSUE TITLE
Erro no autoClose ao não ler QR-code

### ISSUE THREAD

**Issue by Sulivan1999** [billbarsch/myzap#96]
Quando uma nova sessão é iniciada e o QR-code não é lido, após alguns segundos a sessão é fechada de forma automática e junto todas as outra sessões ativas também são, acontece um erro e o servidor caí.

Como eu poderia resolver este problema? Acontece usando o WppConnect e também no Venom

**Comment by gustavohcmelo** [comment]
Cara eu prefiro separar cada sessão em sua própria instância. Se esse serviço é crítico para tua aplicação, não faz muito sentido correr o risco de derrubar tudo. Seja por esse motivo, ou qualquer outro.
